---
title: "Build Klaeger GR Model"
author: "Matthew Berginski"
output: github_document
---

```{r setup, include=FALSE}
library(tidymodels)
library(tidyverse)
library(yardstick)
library(tictoc)
library(here)
```


```{r}
klaeger_data = read_csv(here('data/Klaeger-All.csv')) %>%
	#all of the results with growth 10 don't have a match from the GR vals, remove them
	filter(Growth != 10) %>%
	select(-Drug, -Concentration)

linear_model = linear_reg() %>% 
	set_engine("lm") %>%
	fit(Growth ~ ., data=klaeger_data)

klaeger_LOO_results = data.frame(true_growth = klaeger_data$Growth)
```
# Random Forest

```{r}
tic()
folds <- vfold_cv(klaeger_data, v = 10)

metrics = data.frame()

for (num_trees in seq(1000,5000,by=1000)) {
	
	rf_mod <- 
		rand_forest(trees = num_trees) %>% 
		set_engine("ranger") %>% 
		set_mode("regression")
	
	rf_wf <- 
		workflow() %>%
		add_model(rf_mod) %>%
		add_formula(Growth ~ .)
	
	rf_fit_rs <-
		rf_wf %>%
		fit_resamples(folds)
	
	metrics = rbind(
		metrics,
		collect_metrics(rf_fit_rs) %>% mutate(num_trees = num_trees)
	)
	
}
toc()
# rf_fit = rf_mod %>%
# 	fit(Growth ~ ., data = klaeger_data)

```

```{r}
klaeger_folds <- vfold_cv(klaeger_data, v = 10)

tune_spec <- 
	rand_forest(
		trees = tune()
	) %>% 
	set_engine("ranger") %>% 
	set_mode("regression")

tree_grid <- grid_regular(trees(range = c(2000,5000)),
													levels = 5)

tree_wf <- workflow() %>%
	add_model(tune_spec) %>%
	add_formula(Growth ~ .)

tic()
tree_res <- 
	tree_wf %>% 
	tune_grid(
		resamples = klaeger_folds,
		grid = tree_grid
	)
toc()
```

```{r}
klaeger_folds <- vfold_cv(klaeger_data, v = dim(klaeger_data)[1])

rf_mod <- 
	rand_forest(trees = 1000) %>% 
	set_engine("ranger") %>% 
	set_mode("regression")

rf_wf <- 
	workflow() %>%
	add_model(rf_mod) %>%
	add_formula(Growth ~ .)

tic()
random_forest_LOO <-
	rf_wf %>%
	fit_resamples(klaeger_folds)
toc()
```

## LOO - Manual

```{r}
prediction_results = c()

tic()
for (exclude_row in 1:dim(klaeger_data)[1]) {
	# for (exclude_row in 1:10) {
	klaeger_train = klaeger_data[-exclude_row,]
	klaeger_test = klaeger_data[exclude_row,]
	
	rf_mod <- 
		rand_forest(trees = 1000) %>% 
		set_engine("ranger") %>% 
		set_mode("regression")
	
	rf_wf <- 
		workflow() %>%
		add_model(rf_mod) %>%
		add_formula(Growth ~ .)
	
	rf_fit_rs <-
		rf_mod %>%
		fit(Growth ~ ., data = klaeger_train)
	
	prediction_results = c(prediction_results,
												 predict(rf_fit_rs,klaeger_test)$.pred)
}

klaeger_LOO_results = data.frame(true_growth = klaeger_data$Growth,predicted_growth_RF = prediction_results)
toc()
```

```{r}
rmse = signif(mean(sqrt((klaeger_LOO_results$true_growth - klaeger_LOO_results$predicted_growth_RF)^2)), 3)
r_sq = signif(glance(lm(true_growth ~ predicted_growth_RF, data = klaeger_LOO_results))$r.squared, 3)

results_text = paste0("RMSE: ",rmse,"\n","R\u00B2: ",r_sq)

ggplot(klaeger_LOO_results, aes(x=true_growth, y=predicted_growth_RF)) + 
	geom_point(size=1) +
	geom_smooth(aes(alpha=0.75), method='lm', se=F, lwd=1.5, alpha=0.5) +
	ylim(c(-1,1)) + xlim(c(-1,1)) +
	labs(x="True Growth Rate",y="Random Forest Prediction") +
	geom_text(aes(x=1,y=-1,label=results_text),hjust=1,vjust=0,size=6) +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/klaeger_random_forest.png'),height=5,width=5)

```

# Linear Fit

```{r}
prediction_results_lm = c()

tic()
for (exclude_row in 1:dim(klaeger_data)[1]) {
	# for (exclude_row in 1:10) {
	klaeger_train = klaeger_data[-exclude_row,]
	klaeger_test = klaeger_data[exclude_row,]
	
	lm_fit <- 
		linear_reg() %>% 
		set_engine("lm") %>%
		fit(Growth ~ ., data = klaeger_train)
	
	prediction_results_lm = c(prediction_results_lm,
														predict(lm_fit,klaeger_test)$.pred)
}

klaeger_LOO_results$predicted_growth_LM = prediction_results_lm
toc()
```

# GLMnet - Elastic Net Fit

```{r}
klaeger_folds <- vfold_cv(klaeger_data, v = 20)

tune_spec <- 
	linear_reg(
		penalty = tune(),
		mixture = tune()
	) %>% 
	set_engine("glmnet") %>% 
	set_mode("regression")

# mixture_grid <- grid_regular(min_n(range=c(0,1)), levels=5)
# mixture_vals = data.frame(penalty=seq(0,1,by=0.5))
mixture_vals = grid_regular(mixture(),penalty(range = c(-5,0)), levels = 10)

glmnet_wf <- workflow() %>%
	add_model(tune_spec) %>%
	add_formula(Growth ~ .)

tic()
elastic_res <-
	glmnet_wf %>%
	tune_grid(
		resamples = klaeger_folds,
		grid = mixture_vals
	)
toc()

results = elastic_res %>% collect_metrics() %>% filter(.metric == "rsq") %>% arrange(desc(mean))
```

```{r}
klaeger_folds <- vfold_cv(klaeger_data, v = 150)

glm_fit <- 
	linear_reg(penalty = 0.0215, mixture = 0.333) %>% 
	set_engine("glmnet") %>%
	set_mode("regression")

glmnet_wf <- workflow() %>%
	add_model(glm_fit) %>%
	add_formula(Growth ~ .)

tic()
glmnet_fit_rs <-
	glmnet_wf %>%
	fit_resamples(klaeger_folds)
toc()

glmnet_fit_rs %>% collect_metrics()
# results = elastic_res %>% collect_metrics() %>% filter(.metric == "rsq") %>% arrange(desc(mean))
```

```{r}
prediction_results_glm = c()

tic()
# for (exclude_row in 1:dim(klaeger_data)[1]) {
for (exclude_row in 1:10) {
	klaeger_train = klaeger_data[-exclude_row,]
	klaeger_test = klaeger_data[exclude_row,]
	
	# glm_norm_recipe <-
	# 	recipe(Growth ~ .,
	# 				 data = klaeger_train) %>%
	# 	step_center(all_predictors()) %>%
	# 	step_scale(all_predictors()) %>%
	# 	prep(training = klaeger_train, retain = T)
	
	glm_fit <- 
		linear_reg(penalty = 0.0215, mixture = 0.333) %>% 
		set_engine("glmnet") %>%
		set_mode("regression") %>%
		fit(Growth ~ ., data = klaeger_train)
	
	prediction_results_glm = c(prediction_results_glm,
														 predict(glm_fit,klaeger_test)$.pred)
}

# klaeger_LOO_results$predicted_growth_LM = prediction_results_lm
toc()
```

```{r}
prediction_results_NN = c()

tic()
for (exclude_row in 1:dim(klaeger_data)[1]) {
	# for (exclude_row in 1:10) {
	klaeger_train = klaeger_data[-exclude_row,]
	klaeger_test = klaeger_data[exclude_row,]
	
	lm_fit <- 
		mlp(epochs = 20, hidden_units = 5, dropout = 0.1) %>%
		set_engine("keras") %>%
		set_mode('regression') %>%
		fit(Growth ~ ., data = klaeger_train)
	
	prediction_results_NN = c(prediction_results_NN,
														predict(lm_fit,klaeger_test)$.pred)
}

klaeger_LOO_results$prediction_results_NN = prediction_results_NN
toc()
```



