---
title: "Klaeger/Synergy Binary Model Testing"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)

knitr::opts_knit$set(root.dir = here())

doParallel::registerDoParallel(cores=detectCores() - 2)
```

This code takes the cross validation splits produced from the code in 'process_synergy_klaeger_for_ML' and tests out various models for how well they perform on the binary prediction task.

# Read In Data Sets

```{r}
cell_line_compound_splits = read_rds(here('results/klaeger_synergy_regression_CV_split.rds'))
```

# XGBoost Model Fitting

```{r}
xgb_spec <- boost_tree(
	trees = tune(), 
	tree_depth = tune(),
	min_n = tune(), 
	loss_reduction = tune(),                     
	sample_size = tune(), 
	mtry = tune(),         
	learn_rate = tune(),
) %>% 
	set_engine("xgboost") %>% 
	set_mode("regression")

xgb_grid <- grid_latin_hypercube(
	trees(),
	tree_depth(),
	min_n(),
	loss_reduction(),
	sample_size = sample_prop(),
	#mtry is affected by the size of the data sets, so we need to provide a sample
	#data set for the mtry ranges to be set
	finalize(mtry(), cell_line_compound_splits$CAF),
	learn_rate(),
	size = 100
)

xgb_wf <- workflow() %>%
	add_formula(viability ~ .) %>%
	add_model(xgb_spec)
```

```{r}
tic()

if (! file.exists(here('results/xgboost_regression_models/CAF.rds'))) {
	xgb_res_CAF <- tune_grid(
		xgb_wf,
		resamples = cell_line_compound_splits$CAF,
		grid = xgb_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/xgboost_regression_models/CAF.rds'), compress = 'gz')
}

if (! file.exists(here('results/xgboost_regression_models/P1004.rds'))) {
	xgb_res_P1004 <- tune_grid(
		xgb_wf,
		resamples = cell_line_compound_splits$P1004,
		grid = xgb_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/xgboost_regression_models/P1004.rds'), compress = 'gz')
}

if (! file.exists(here('results/xgboost_regression_models/P1304.rds'))) {
	xgb_res_P1304 <- tune_grid(
		xgb_wf,
		resamples = cell_line_compound_splits$P1304,
		grid = xgb_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/xgboost_regression_models/P1304.rds'), compress = 'gz')
}
toc()
```

# Random Forest Model Fitting

```{r}
rand_forest_spec <- rand_forest(
	trees = tune(), 
	mtry = tune(),
	min_n = tune()
) %>% set_engine("ranger") %>% 
	set_mode("regression")

rand_forest_grid <- grid_latin_hypercube(
	trees(c(1000,5000)),
	min_n(),
	finalize(mtry(),cell_line_compound_splits$CAF),
	size = 100
)

rand_forest_wf <- workflow() %>%
	add_formula(viability ~ .) %>%
	add_model(rand_forest_spec)
```

```{r}
tic()
if (! file.exists(here('results/rand_forest_regression_models/CAF.rds'))) {
	rand_forest_res_CAF <- tune_grid(
		rand_forest_wf,
		resamples = cell_line_compound_splits$CAF,
		grid = rand_forest_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/rand_forest_regression_models/CAF.rds'), compress = 'gz')
}

if (! file.exists(here('results/rand_forest_regression_models/P1004.rds'))) {
	rand_forest_res_P1004 <- tune_grid(
		rand_forest_wf,
		resamples = cell_line_compound_splits$P1004,
		grid = rand_forest_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/rand_forest_regression_models/P1004.rds'), compress = 'gz')
}

if (! file.exists(here('results/rand_forest_regression_models/P1304.rds'))) {
	rand_forest_res_P1304 <- tune_grid(
		rand_forest_wf,
		resamples = cell_line_compound_splits$P1304,
		grid = rand_forest_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/rand_forest_regression_models/P1304.rds'), compress = 'gz')
}
toc()
```

# SVM Model Fitting

```{r}
svm_spec <- svm_poly(
	cost = tune(), 
	degree = tune(),
	scale_factor = tune()
) %>% set_engine("kernlab") %>% 
	set_mode("regression")

svm_grid <- grid_latin_hypercube(
	cost(),
	degree(),
	scale_factor(),
	size = 100
)

svm_wf <- workflow() %>%
	add_formula(viability ~ .) %>%
	add_model(svm_spec)
```

```{r}
tic()
if (! file.exists(here('results/svm_regression_models/CAF.rds'))) {
	svm_res_CAF <- tune_grid(
		svm_wf,
		resamples = cell_line_compound_splits$CAF,
		grid = svm_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/svm_regression_models/CAF.rds'), compress = 'gz')
}

if (! file.exists(here('results/svm_regression_models/P1004.rds'))) {
	svm_res_P1004 <- tune_grid(
		svm_wf,
		resamples = cell_line_compound_splits$P1004,
		grid = svm_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/svm_regression_models/P1004.rds'), compress = 'gz')
}

if (! file.exists(here('results/svm_regression_models/P1304.rds'))) {
	svm_res_CAF <- tune_grid(
		svm_wf,
		resamples = cell_line_compound_splits$P1304,
		grid = svm_grid,
		control = control_grid(save_pred = TRUE)
	) %>% write_rds(here('results/svm_regression_models/P1304.rds'), compress = 'gz')
}
toc()
```